# Uses PORT env var injected by Render/Railway; defaults to 8080 locally
server.port=${PORT:8080}
spring.application.name=bfhl-api

# Student Details (used in response)
app.user.first-name=Keshav
app.user.last-name=Banger
app.user.dob=01052006
app.user.email=Keshavbanger230815@acropolis.in
app.user.roll-number=0827cs231129
